#!/bin/bash
# GOAL: single script to set up, build, and run BRCP85LENS portion of LENS
#       (branch off of B20TRLENS run from other script)
#
# This script:
# * Get 2006 rest files from either campaign or scratch archive
# * Run 2006 - 2025 (20 years), then fork to continue future run
# First test ran ~18.5 SYPD => 5 years per 8 hour submission should suffice

# 1. Error checks: must be on cheyenne and must pass single command line argument
running_on=`hostname | cut -c 1-8`
if [ ${running_on} != "cheyenne" ]; then
  echo "Can not run on `hostname`, need to be on cheyenne"
  exit 1
fi

if [ $# != 1 ]; then
  echo "usage: $0 CASEID"
  echo "       CASEID -- id of CESM LE case to be cloned"
  exit 1
fi

#    Also, abort if any command returns an error
set -e

# 2. Set some environment variables
cesmroot=/glade/work/mlevy/codes/CESM/cesm1_1_2_LENS_n21
caseroot=/glade/work/mlevy/codes/pinatubo-LE/cases
compset=BRCP85LENS
res=f09_g16
refcase=b.e11.B20TRC5CNBDRD_no_pinatubo.${res}.$1
case=b.e11.BRCP85C5CNBDRD_no_pinatubo.${res}.$1
restdir1=/glade/scratch/mlevy/archive/${refcase}/rest/2006-01-01-00000
restdir2=/glade/campaign/univ/udeo0005/cesmLE_no_pinatubo/restarts/no_pinatubo/${refcase}/2006-01-01-00000
rundir=/glade/scratch/mlevy/${case}/run

# Verify that restarts are available
if [ ! -d ${restdir1} ]; then
  ssh casper "ls ${restdir2} > /dev/null 2>&1" || RESTNOTFOUND=TRUE
  if [ "$RESTNOTFOUND" ]; then
    echo "${restdir1} does not exist"
    echo "${restdir2} does not exist"
    echo "Can not stage restarts"
    exit 1
  fi
fi

# 3. Generate case
#    a. run create_newcase
echo "Creating ${case} to run from 2006..."
cd ${cesmroot}/scripts
./create_newcase -compset ${compset} -res ${res} -case ${caseroot}/${case} -mach cheyenne
cd ${caseroot}/${case}
#    b. Set up hybrid run using correct REFCASE
./xmlchange RUN_REFCASE=${refcase}
#    b. run cesm_setup
./cesm_setup
#    c. xml changes, update user_nl_cam
./xmlchange STOP_N=5,STOP_OPTION=nyears,RESUBMIT=3
#    d. modify run script: add account to charge, update wall time
sed -i s/01:50/08:00/ ${case}.run
sed -i 's/###PBS -A/#PBS -A UDEO0005/' ${case}.run
#    e. stage restart files
if [ -d ${restdir1} ]; then
  echo "Copying restarts from archive..."
  cp -v ${restdir1}/* ${rundir}/
else
  echo "Copying restarts from campaign via scp (using casper). May prompt for UCAS_Token_Response..."
  scp casper:${restdir2}/* ${rundir}/
fi
#    f. modify user_nl_cice to include some terms in daily stream
sed -i -e '/f_aicen/ s/xh/dh/' -e '/fswthru/ s/xh/dh/' -e '/f_uvel/ s/xh/dh/' -e '/f_vvel/ s/xh/dh/' user_nl_cice
#    g. build and submit
qcmd -- ./${case}.build
./${case}.submit
